# Site Settings
title: Event Registration API using Nest JS
author:
  name: Utkal Nayak
  email: nayak.utkal@gmail.com

# Build settings
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme 
